### PR TITLE
Adds default color when zone is after the max number of keys to light.

### PR DESCRIPTION
**Pull request by trevlar**
@daskeyboard @fabiendv I've added the changes in the current version of master that is on version "1.0.6" of the cpu-usage app. Please review and merge if everything is good. Thank you!

### CODE REVIEW

**Review by fabiendv — CHANGES_REQUESTED** [review]
Can you remove the _if the color exists_ inside applyConfig() and the comment also ? 
It does not make sense to stop the config because of #ff0000 value and allow #fe0000.

**Comment by trevlar** [comment]
> Can you remove the _if the color exists_ inside applyConfig() and the comment also ?
> It does not make sense to stop the config because of #ff0000 value and allow #fe0000.

Does it need the applyConfig method or can I remove that also?

**Comment by trevlar** [comment]
Your right it didn't make sense. The more I think about it though allowing any color selection is best.

no sense

**Review by fabiendv — APPROVED** [review]

**Comment by fabiendv** [comment]
It is easier this way! 
I will deploy today. Thanks.

**Pull request merged**
